### ISSUE TITLE
Input parameter is changed as well

### ISSUE THREAD

**Issue by mbogh** [agilecreativity/filename_cleaner#2] opened 2015-09-26 18:21 UTC
Hi,

If a pass in a variable into `FilenameCleaner.sanitize()` the variable gets changed as well.
Is this expected behaviour or a bug?

``` ruby
head :001 > require "filename_cleaner"
 => true 
head :002 > name = "Global Variables"
 => "Global Variables" 
head :003 > new_name = FilenameCleaner.sanitize(name, '_', false)
 => "Global_Variables" 
head :004 > name
 => "Global_Variables"
```

**Comment by agilecreativity** [comment] 2015-11-23 12:36
Hi @mbogh,
Sorry for the late reply. I think it is by design or side effect from the following code.

```
  def replace_dot(string, replace = nil)
      string.gsub!(/#{Regexp.quote(DOT)}+/, replace) if replace
      string
  end
```

This is the very easy to fix though. Is there specific use case that you need to use the old name?

**Comment by mbogh** [comment] 2015-11-23 14:14
Hi @agilecreativity 

I have given it a try in #3, my Ruby is not that sharp so please feel free to give feedback if the style is a bit off :smile_cat:

**Comment by agilecreativity** [comment] 2015-11-24 11:19
@mbogh Thanks for your PR! I have now merged your changes and minor update to the gem.
Happy hacking. Please report any issue if you find one.

**Closed as completed by agilecreativity** 2015-11-24 11:19 UTC
